name: Java Project Deployment

on:
  push:
    branches:
      - master # Adjust this branch name based on your repository's default branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      - name: Wait for MySQL to be ready
        run: sleep 30  # Wait for the MySQL container to be ready

      - name: Check MySQL service status
        run: mysqladmin ping -h 127.0.0.1 -u root -proot

      - name: Import SQL dump
        run: mysql -h 127.0.0.1 -u root -proot < SQL/InventoryDB.sql

      - name: Run Java application
        run: java -jar jar/InventoryManagement.jar
